apps/noticias/urls.py
from django.urls import path
from .import views

app_name ='noticias'

urlpatterns = [
    path('', views.ListarNoticias, name ='listar'),
   

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from .import views
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('nosotros/',views.Nosotros, name = 'nosotros'),
    path('noticias/', include('apps.noticias.urls')),
]

apps/noticias/models.py
from django.db import models

# Create your models here.
class Categoria(models.Model):
    nombre=models.CharField(max_length=50)
    
    def __str__(self):  # Corregido aquí
        return self.nombre

class Noticias(models.Model):
    titulo= models.CharField(max_length=50)
    contenido= models.TextField()
    imagenes=models.ImageField(upload_to='noticias')
    fecha_publicacion=models.DateTimeField(auto_now_add=True)
    categoria_noticia=models.ForeignKey(Categoria, on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.titulo

apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
    pass
    

apps/noticias/views.py
from django.shortcuts import render

# Create your views here.
def ListarNoticias(request):
    
    return render(request,'noticias/listar.html')

apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

def Home(request):
    return render(request, 'home.html')

def Nosotros(request):
    return render(request, 'nosotros.html')
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>Mi Blog{% block titulo %}{% endblock titulo %}</title>

</head>
<body class ="contenedor">
    {% block contenido %}

    {% endblock contenido%}
    <a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
    <a href="{% url 'home' %}">VOLVER AL INICIO</a>
    <a href="{% url 'noticias:listar' %}">NOTICIAS</a>
    
    

</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}Home{% endblock titulo %}

{% block contenido %}

  <h2>Hola Mundo</h2>
  
{% endblock contenido %}

templates/nosotros.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}Nosotros{% endblock titulo %}

{% block contenido %}

  <h2>soy de la comision 6</h2>
  
{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}Noticias{% endblock titulo %}

{% block contenido %}

  <h2>aca estan las noticias</h2>
  
{% endblock contenido %}